name: docs

on: 
  push:
    branches:
      - master
    
jobs:
  docs:    
    runs-on: ubuntu-latest
    steps:
    - name: Build docs
      run: make docs
    - name: Pip freeze for used by stats
      run: make requirements
